### ISSUE TITLE
QA_Huckel Molecular Orbital Theory_Experiment title_differs

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#17]
**Defect Description**:
In all the pages of "Huckel Molecular Orbital Theory" experiment, title of the experiment is given as **Huckel Molecular Orbital Theory for Conjugated hydrocarbons**. Need to change the name in order to maintain the contingency of the experiment.

**Actual Result**:
In all the pages of "Huckel Molecular Orbital Theory" experiment, title of the experiment is given as **Huckel Molecular Orbital Theory for Conjugated hydrocarbons**.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_expname 5 _i19](https://cloud.githubusercontent.com/assets/13479177/18346624/bafc2c8e-75da-11e6-9074-0abbfc9df940.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, the name of the experiment is given as **Huckel Molecular Orbital Theory**. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #17
