### ISSUE TITLE
QA_Transition State Calculation for a SN2 reaction_Quizzes_No cancel button is provided 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#22]
**Defect Description**:
In the Quizzes page of "Transition State Calculation for a SN2 reaction" experiment, Cancel button is not provided. Need to provide the Cancel button in order to reset the options in case if the user selects wrong answers.

**Actual Result**:
In the Quizzes page of "Transition State Calculation for a SN2 reaction" experiment, Cancel button is not provided.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qc_qcl_quiz 7 _i25](https://cloud.githubusercontent.com/assets/13479177/18348081/ba9cdc7c-75e2-11e6-8d66-84c9ed1d1aa3.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, by default there will be **Check** & **Show answer** buttons in the quiz page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #22
