### ISSUE TITLE
QA_Transition State Calculation for a SN2 reaction_Experiment title_differs

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#24]
**Defect Description**:
In all the pages of "Transition State Calculation for a SN2 reaction" experiment, title of the experiment is given as **Transition state calcuation for a simple organic chemistry reaction**. Need to change the name in order to maintain the contingency of the experiment.

**Actual Result**:
In all the pages of "Transition State Calculation for a SN2 reaction" experiment, title of the experiment is given as **Transition state calcuation for a simple organic chemistry reaction**.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_expname 7 _i26](https://cloud.githubusercontent.com/assets/13479177/18348239/abdf6d52-75e3-11e6-8e84-a3ddb7eb220d.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, numbering is not required for the experiments. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #24
