### ISSUE TITLE
QA_Eigen Systems: Geometrical Interpretation_url_name differing

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#25]
**Defect Description**:
In all the pages of "Eigen Systems: Geometrical Interpretation" experiment, in the URL numbering for this experiment is given as exp7. Where as this is the 8th experiment in the list.

**Actual Result** :
In all the pages of "Eigen Systems: Geometrical Interpretation" experiment, in the URL numbering for this experiment is given as exp7.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_url 8 _i28](https://cloud.githubusercontent.com/assets/13479177/18862050/14a6950e-84a3-11e6-8bf3-4224158422c0.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, numbering of the experiments are not necessary, experiments are listed with their names. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #25
