### ISSUE TITLE
QA_Eigen Systems: Geometrical Interpretation_Quizzes_No cancel button is provided

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#26]
**Defect Description**:
In the Quizzes page of "Eigen Systems: Geometrical Interpretation" experiment, Cancel button is not provided. Need to provide the Cancel button in order to reset the options in case if the user selects wrong answers.

**Actual Result**:
In the Quizzes page of "Eigen Systems: Geometrical Interpretation" experiment, Cancel button is not provided.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_quiz 8 _i29](https://cloud.githubusercontent.com/assets/13479177/18862610/bd372ee2-84a6-11e6-907b-7a65126b4606.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, by default there will be **Check** & **Show answer** buttons in the quiz page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #26
