### ISSUE TITLE
QA_Geometry Optimization of Molecules_url_name differing

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#27]
**Defect Description**:
In all the pages of "Geometry Optimization of Molecules" experiment, in the URL numbering for this experiment is given as exp1. Where as this is the 9th experiment in the list.

**Actual Result** :
In all the pages of "Geometry Optimization of Molecules" experiment, in the URL numbering for this experiment is given as exp1.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_url 9 _i30](https://cloud.githubusercontent.com/assets/13479177/18865359/4fb75e74-84b4-11e6-8568-bfa788adc08c.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, numbering of the experiments are not necessary, experiments are listed with their names. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #27
