### ISSUE TITLE
QA_Geometry Optimization of Molecules_Quizzes_No cancel button is provided

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#28]
**Defect Description**:
In the Quizzes page of "Geometry Optimization of Molecules" experiment, Cancel button is not provided. Need to provide the Cancel button in order to reset the options in case if the user selects wrong answers.

**Actual Result**:
In the Quizzes page of "Geometry Optimization of Molecules" experiment, Cancel button is not provided.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_quiz 9 _i31](https://cloud.githubusercontent.com/assets/13479177/18865552/4f438b9c-84b5-11e6-9f3f-e19889edc1a6.png)

**Comment by sravanthimodepu** [comment]
As all the labs are running on open-edx, by default there will be **Check** & **Show answer** buttons in the quiz page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #28
