### ISSUE TITLE
QA_Geometry Optimization of Molecules_Further Readings_Links are not working

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#29]
**Defect Description**:
The links given in the Further Readings page of "Geometry Optimization of Molecules" experiment of this lab are not working. 1st link seems to be irrelevant for this experiment and the rest two are redirecting to error page. Where as the links should redirect to the appropriate pages.  

**Actual Result**:
The links given in the Further Readings page of "Geometry Optimization of Molecules" experiment of this lab are not working. 1st link seems to be irrelevant for this experiment and the rest two are redirecting to error page. 

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_qcl_fr-links_i32](https://cloud.githubusercontent.com/assets/13479177/18866783/e3311770-84ba-11e6-94eb-f72ba516156b.png)

![qa_qcl_fr-links_i33](https://cloud.githubusercontent.com/assets/13479177/18866816/fb315f6a-84ba-11e6-88e4-0fc8c3add7b9.png)

**Comment by sravanthimodepu** [comment]
Updated the further readings page with the appropriate links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue re opened as all the 3 links are related to Simple Harmonic Motion experiment of Structural Dynamics lab. Given a clarification on the relation of the links for current experiment, shall close the issue.
