### ISSUE TITLE
QA_UV-Visible Spectroscopy of Conjugated Systems_Experiment_Disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#33]
Defect Description :
In the experiment section of "UV-Visible Spectroscopy of Conjugated Molecules" experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both the full and the small screens.

Actual Result :
In the experiment section of "UV-Visible Spectroscopy of Conjugated Molecules" experiment, the experiment is disabled in the small screen. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i02](https://cloud.githubusercontent.com/assets/13479177/26668463/78857a86-46c7-11e7-9da4-618dc3fe37d0.png)

**Comment by sravanthimodepu** [comment]
There is an inconsistency in the small screen to load the simulations and it runs with java3d, it loads slowly.. Hence differing the issue.

**Comment by BSravanthi** [comment]
Its not a differed issue, The experiment itself is not opening on small screen. Though the experiment runs with Java 3d, it does not make any difference for enabling the experiment in small scree. The experiment should open in both the screens. Later if Java 3d is disabled in the machine the concerned message should be poped up.

**Comment by BSravanthi** [comment]
Closing the issue #33 as now the experiment is enabled in the small screen too.
