### ISSUE TITLE
QA_UV-Visible Spectroscopy of Conjugated Systems_Experiment_broken-links

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#34]
Defect Description :
In the experiment section of "UV-Visible Spectroscopy of Conjugated Molecules" experiment, the link given in the experiment page is navigating to error page.

Actual Result :
In the experiment section of "UV-Visible Spectroscopy of Conjugated Molecules" experiment, the link given in the experiment page is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i01](https://cloud.githubusercontent.com/assets/13479177/26668877/454b5ff8-46c9-11e7-8670-3ddd0fa7847d.png)

**Comment by sravanthimodepu** [comment]
Corrected the Link. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue.

**Comment by BSravanthi** [comment]
Closed #34
