### ISSUE TITLE
QA_UV-Visible Spectroscopy of Conjugated Molecules_Quizzes_User

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#35]
Defect Description :
In the Quizzes page of the UV-Visible Spectroscopy of Conjugated Molecules experiment, the "Show Answer" button is disabled when we log in as user. Need to provide the button in order to provide the answers to the users.

Actual Result :
In the Quizzes page of the UV-Visible Spectroscopy of Conjugated Molecules experiment, the "Show Answer" button is disabled when we log in as user.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_i03](https://cloud.githubusercontent.com/assets/13479177/26669023/f0210b58-46c9-11e7-9336-f204acba67b2.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #35
