### ISSUE TITLE
QA_Order-of-the-menu_UV-Visible Spectroscopy of Conjugated Molecules

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#36]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i04](https://cloud.githubusercontent.com/assets/13479177/26669217/a8bb06dc-46ca-11e7-8ce6-07e2fefd309c.png)

**Comment by sravanthimodepu** [comment]
Corrected the order to "Introduction, Theory, Objective, Manual, Experiment, Quizzes, Further readings and Feedback". Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #36
