### ISSUE TITLE
QA_Vib-rotational Spectroscopy of Hydrogen Chloride_Experiment_Disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#37]
Defect Description :
In the experiment section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both the full and the small screens.

Actual Result :
In the experiment section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the experiment is disabled in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i05](https://cloud.githubusercontent.com/assets/13479177/26671393/f01b3daa-46d2-11e7-8235-26b1200b45ee.png)

**Comment by sravanthimodepu** [comment]
There is an inconsistency in the small screen to load the simulations and it runs with java3d. Hence it loads slowly..

**Comment by BSravanthi** [comment]
Its not that the loading time due to java3D. The experiment is not at all ported in the small screen. 
Closed #37
