### ISSUE TITLE
QA_Vib-rotational Spectroscopy of Hydrogen Chloride_Experiment_broken-links

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#38]
Defect Description :
In the experiment section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the link given in the experiment page is navigating to error page.

Actual Result :
In the experiment section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the link given in the experiment page is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i06](https://cloud.githubusercontent.com/assets/13479177/26671462/39e95c78-46d3-11e7-906b-a3c9c9b17fe4.png)

**Comment by sravanthimodepu** [comment]
Corrected the Link. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue

**Comment by BSravanthi** [comment]
Closed #38
