### ISSUE TITLE
QA_Vib-rotational Spectroscopy of Hydrogen Chloride _Quizzes_discrepancy

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#39]
Defect Description :
In the Quizzes page of the Vib-rotational Spectroscopy of Hydrogen Chloride experiment, found discrepancy in the functionality of the "Show Answer" button. The button is disabled when we choose wrong answers. We can observe the button gets appear when we select right answers and click on "Check" button.

Actual Result :
In the Quizzes page of the Vib-rotational Spectroscopy of Hydrogen Chloride experiment, found discrepancy in the functionality of the "Show Answer" button. The button is disabled when we choose wrong answers. We can observe the button gets appear when we select right answers and click on "Check" button.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_qc_i07](https://cloud.githubusercontent.com/assets/13479177/26671786/6856edd6-46d4-11e7-8f16-fec5e17b172d.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section, even if we select the wrong answers . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue as the functionality of both the buttons are missed where as last phase of testing the functionality of the check button is present and show answer button is present with discrepancy. Such inconsistency need to be fixed in order to maintain the quality of the services.

**Comment by sravanthimodepu** [comment]
This issue to be fixed by the system's team. Hence keeping the issue on hold.
