### ISSUE TITLE
QA_Vib-rotational Spectroscopy of Hydrogen Chloride_Further Readings_Broken-links

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#40]
Defect Description :
In the Further Readings section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the 2nd and 3rd links are navigating to error page.

Actual Result :
In the Further Readings section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the 2nd and 3rd links are navigating to error page.
Need to correct/separate the order for the links and other references. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i08](https://cloud.githubusercontent.com/assets/13479177/26672080/72de4aa0-46d5-11e7-9bdf-e527082ce5f6.png)

**Comment by sravanthimodepu** [comment]
Updated the further readings page with appropriate links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue re opened as all the 3 links are related to Simple Harmonic Motion experiment of Structural Dynamics lab. Given a clarification on the relation of the links for current experiment, shall close  the issue.
