### ISSUE TITLE
QA_Vib-rotational Spectroscopy of Hydrogen Chloride_Further Readings_irrelevant-links

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#41]
Defect Description :
In the Further readings section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the 1st link is seems to be irrelevant. 

Actual Result :
In the Further readings section of "Vib-rotational Spectroscopy of Hydrogen Chloride" experiment, the 1st link is seems to be irrelevant. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i08](https://cloud.githubusercontent.com/assets/13479177/26672150/c9662c44-46d5-11e7-8726-6d6ea2e28e04.png)

**Comment by sravanthimodepu** [comment]
Corrected the link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Still given the same link

**Comment by BSravanthi** [comment]
Referring the issue to #40
