### ISSUE TITLE
QA_Geometry Optimization using ab initio quantum calculations_spelling-mistake-in-the-title.

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#43]
Defect Description :
Found spelling mistake in the title of the experiment.

Actual Result :
Found spelling mistake in the title of the experiment.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i10](https://cloud.githubusercontent.com/assets/13479177/26672423/b2bdac46-46d6-11e7-8c0e-84b6abbbb0aa.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake of the experiment  name

**Comment by BSravanthi** [comment]
Closed #43
