### ISSUE TITLE
QA_Geometry Optimization using ab initio quantum calculations_Theory

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#44]
Defect Description :
In the Theory section of the "Geometry Optimization using ab initio quantum calculations" experiment, the 1st word has been changed while porting. 

Actual Result :
In the Theory section of the "Geometry Optimization using ab initio quantum calculations" experiment, the 1st word has been changed while porting. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i11](https://cloud.githubusercontent.com/assets/13479177/26672601/5a81c62e-46d7-11e7-857b-e5588211f4b7.png)

**Comment by sravanthimodepu** [comment]
Corrected the first word in the theory section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #44
