### ISSUE TITLE
QA_Geometry Optimization using ab initio quantum calculations_Theory_numbering-&-junk-characters.

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#45]
Defect Description :
In the Theory section of the "Geometry Optimization using ab initio quantum calculations" experiment, found that the numbering for all the points is given as 1. Instead the numbering should be continuous. And found junk character.

Actual Result :
In the Theory section of the "Geometry Optimization using ab initio quantum calculations" experiment, found that the numbering for all the points is given as 1. Instead the numbering should be continuous. And found junk character.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment: 
![qa_oe_qc_i12](https://cloud.githubusercontent.com/assets/13479177/26672718/e06a06a2-46d7-11e7-938e-5471c015f38c.png)

**Comment by sravanthimodepu** [comment]
Aligned the numbers in a proper order and removed the junk characters in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #45
