### ISSUE TITLE
QA_Geometry Optimization using ab initio quantum calcuations_Quiz

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#47]
Defect Description :
In the Quizzes page of the Geometry Optimization using ab initio quantum calcuations experiment, the "Show Answer" button is disabled when we log in as user. Need to provide the button in order to provide the answers to the users.

Actual Result :
In the Quizzes page of the Geometry Optimization using ab initio quantum calcuations experiment, the "Show Answer" button is disabled when we log in as user.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_qc_i14](https://cloud.githubusercontent.com/assets/13479177/26673485/b3949784-46da-11e7-87a0-71621c860c4f.png)

**Comment by sravanthimodepu** [comment]
Check button and the show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue though the Show answer button is provided. Because the functionality of the button is missing. 
In the above screen shot, the functionality of the Check button is present. Where as in this phase of testing it is missed. 
Found inconsistency. Hence re opening the issue.

**Comment by sravanthimodepu** [comment]
This issue to be fixed by the system's team. Hence keeping the issue on hold.
