### ISSUE TITLE
QA_Huckel Molecular Orbital_Theory_improper-porting

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#51]
Defect Description :
In the Theory section of "Huckel Molecular Orbital" experiment, the content is not ported properly. 

Actual Result :
In the Theory section of "Huckel Molecular Orbital" experiment, the content is not ported properly. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i18](https://cloud.githubusercontent.com/assets/13479177/26674542/72a5109c-46de-11e7-89e8-cea8b0e54ece.png)

**Comment by sravanthimodepu** [comment]
Updated the theory page with the missing content. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #51
