### ISSUE TITLE
QA_Huckel Molecular Orbital_Theory_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#52]
Defect Description :
Found spelling mistake in the theory section of Huckel Molecular Orbital experiment.

Actual Result :
Found spelling mistake in the theory section of Huckel Molecular Orbital experiment.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i19](https://cloud.githubusercontent.com/assets/13479177/26674676/d56433de-46de-11e7-81f8-1dda6137cef8.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #52
