### ISSUE TITLE
QA_Huckel Molecular Orbital Theory_Quiz_functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#54]
Defect Description :
In the Quizzes page of the Huckel Molecular Orbital Theory experiment, the "Show Answer" button is disabled when we log in as user. Need to provide the button in order to provide the answers to the users.
Check button functionality is also improper. 

Actual Result :
In the Quizzes page of the Huckel Molecular Orbital Theory experiment, the "Show Answer" button is disabled when we log in as user. Check button functionality is also improper. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_qc_i21](https://cloud.githubusercontent.com/assets/13479177/26675105/3b352e60-46e0-11e7-8977-f3530f80e85c.png)

**Comment by sravanthimodepu** [comment]
This issue to be fixed by the system's team. Hence keeping the issue on hold.
