### ISSUE TITLE
QA_Conformational Analysis of 1,2-dichloroethane_Quizzes_discrepancy

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#57]
Defect Description :
In the Quizzes page of the **Conformational Analysis of 1,2-dichloroethane** experiment, found discrepancy in the functionality of the "Show Answer" button. The button is disabled when we choose wrong answers. We can observe the button gets appear when we select right answers and click on "Check" button.

Actual Result :
In the Quizzes page of the **Conformational Analysis of 1,2-dichloroethane** experiment, found discrepancy in the functionality of the "Show Answer" button. The button is disabled when we choose wrong answers. We can observe the button gets appear when we select right answers and click on "Check" button.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_qc_i24](https://cloud.githubusercontent.com/assets/13479177/26675505/e393deca-46e1-11e7-8b59-8285bd3a54e8.png)

**Comment by sravanthimodepu** [comment]
There is no dicripency in the quiz page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue.

**Comment by sravanthimodepu** [comment]
This issue to be fixed by the system's team. Hence keeping the issue on hold.
