### ISSUE TITLE
QA_Conformational Analysis of 1,2-dichloroethane_Further Readings_Broken-links

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#58]
Defect Description :
In the Further Readings section of "Conformational Analysis of 1,2-dichloroethane" experiment, the given link is navigating to error page.

Actual Result :
In the Further Readings section of "Conformational Analysis of 1,2-dichloroethane" experiment, the given link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i25](https://cloud.githubusercontent.com/assets/13479177/26675672/770c496c-46e2-11e7-8f78-a12ba2dec011.png)

**Comment by sravanthimodepu** [comment]
Removed the link, as it is not working.

**Comment by BSravanthi** [comment]
Issue is still persisting. Hence reopening the issue.

**Comment by sravanthimodepu** [comment]
Removed the link, as there is no related link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #58
