### ISSUE TITLE
QA_Transition State Calculation for a SN2 reaction_Theory_incomplete-content

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#60]
Defect Description :
In the Theory section of the "Transition State Calculation for a SN2 reaction" experiment, the complete content has not been ported including image.(The image is broken in vlabs page.)

Actual Result :
In the Theory section of the "Transition State Calculation for a SN2 reaction" experiment, the complete content has not been ported including image.(The image is broken in vlabs page.)

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_qc_i27](https://cloud.githubusercontent.com/assets/13479177/26676787/e3afd350-46e6-11e7-9960-93bef56aa714.png)

**Comment by sravanthimodepu** [comment]
Image is missing in the theory page of vlab.co.in.
