### ISSUE TITLE
QA_UV-Visible Spectroscopy of Conjugated Molecules_Quizzes_discrepancy 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/quantum-chemistry-iiith#62]
Defect Description :
While testing issue #35 found that In the Quizzes page of the UV-Visible Spectroscopy of Conjugated Molecules experiment, the functionality of both the buttons are not present. Where as in the latest phase of testing the "Check" button was working fine. But in the next phase of testing the functionality  is missed for both the buttons. Need to fix the discrepancy. 

Actual Result :
While testing issue #35 found that In the Quizzes page of the UV-Visible Spectroscopy of Conjugated Molecules experiment, the functionality of both the buttons are not present. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_qc_i28](https://user-images.githubusercontent.com/13479177/27723250-c7eb942e-5d89-11e7-8d74-4f610166b39f.png)

**Comment by sravanthimodepu** [comment]
This issue needs to be fixed by the system's team. Hence keeping the issue on hold.
