### ISSUE TITLE
Quantum-Chemistry_UV-Visible-Spectroscopy-of-Conjugated-Systems_Quizzes

### ISSUE THREAD

**Issue by kurasaiteja** [virtual-labs/quantum-chemistry-iiith#79]
**Defect description :in the given quiz consider a case of we not attempting a question.after we click on submit option the unattempted question is also shown as wrong which is not right.to prevent this an instruction to attempt all questions must be given beforehand or the unattempted question must not be graded at all. steps to reproduce the issue: open the virtual labs link "http://vlab.co.in" click on iiit hyderabad under the participating institutes option present on left side of your page. * click on hyperlink of quantum chemistry lab. * click on list of experiments and any experiment . * click on quizzes option. expected result: unattempted answer to be not graded. actual result: unattempted answer is displayed as wrong. screenshots:

![capture](https://user-images.githubusercontent.com/39938013/42115168-79fe7fba-7c0f-11e8-8689-76cb580751ac.PNG)

**Comment by kurasaiteja** [comment]
commit id is: a68c36e
There is only one results file for all quizzes in this experiment.My fix ensures 
1)only the attempted questions will be evaluated(ALL unattempted questions are ungraded because attempting all questions isnt mandatory always.Instead we can leave them ungraded)
2)An alert pops up when no questions are attempted

**Comment by aakarsh7599** [comment]
Valid fix

**Comment by kurasaiteja** [comment]
@fireballpoint1 Please check this out

**Comment by fireballpoint1** [comment]
Fix is validated and can be moved to production, krusaiteja , S3
